<?php

/**
 * Frequently asked questions per service, rendered visibly on the service page
 * and mirrored as FAQPage structured data.
 *
 * Ground rules for anything added here:
 *  - Answer the question in the first sentence. These are read as much by
 *    people scanning as by Google.
 *  - No invented numbers, prices or response-time promises. Where the honest
 *    answer is "it depends", say what it depends on.
 *  - Legal and regulatory statements stay at the level that is actually true
 *    everywhere in Flanders; anything municipality-specific is deferred to
 *    "we check that for you" instead of asserted.
 */
return [

    'heating' => [
        'nl' => [
            ['question' => 'Hoe vaak moet een verwarmingsketel onderhouden worden?', 'answer' => 'In Vlaanderen is een periodieke onderhoudsbeurt wettelijk verplicht: voor toestellen op gas om de twee jaar, voor toestellen op stookolie jaarlijks. Naast de wettelijke verplichting houdt een onderhoud het rendement op peil en worden beginnende defecten opgemerkt voor ze tot een panne leiden.'],
            ['question' => 'Ik heb wel verwarming maar geen warm water — wat kan dat zijn?', 'answer' => 'Bij een combiketel wijst dat vaak op de warmwaterfunctie zelf: een vervuilde of verkalkte warmtewisselaar, een defecte driewegklep of een sensor die de warmwatervraag niet meer doorgeeft. Omdat de verwarming wel blijft werken, is het zelden de brander. Vermeld het merk, het model en eventuele foutcode bij uw aanvraag, dan kunnen wij het juiste onderdeel meteen meenemen.'],
            ['question' => 'Wanneer is een ketel vervangen voordeliger dan herstellen?', 'answer' => 'Dat hangt af van de leeftijd van het toestel, de beschikbaarheid van onderdelen en de kostprijs van de herstelling ten opzichte van een nieuwe installatie. Zijn onderdelen voor uw type niet meer leverbaar, dan is herstellen meestal uitstel. Wij geven bij de diagnose eerlijk aan wanneer een herstelling nog de betere keuze is.'],
        ],
        'fr' => [
            ['question' => 'À quelle fréquence une chaudière doit-elle être entretenue ?', 'answer' => 'En Flandre, un entretien périodique est légalement obligatoire : tous les deux ans pour les appareils au gaz, chaque année pour les appareils au mazout. Au-delà de l\'obligation, un entretien maintient le rendement et permet de repérer les défauts naissants avant qu\'ils ne provoquent une panne.'],
            ['question' => 'J\'ai du chauffage mais plus d\'eau chaude — quelle en est la cause ?', 'answer' => 'Sur une chaudière combinée, cela pointe souvent vers la fonction eau chaude elle-même : un échangeur encrassé ou entartré, une vanne trois voies défectueuse ou une sonde qui ne transmet plus la demande. Comme le chauffage continue de fonctionner, le brûleur est rarement en cause. Indiquez la marque, le modèle et l\'éventuel code d\'erreur dans votre demande afin que nous puissions emporter la bonne pièce.'],
            ['question' => 'Quand vaut-il mieux remplacer que réparer ?', 'answer' => 'Cela dépend de l\'âge de l\'appareil, de la disponibilité des pièces et du coût de la réparation par rapport à une nouvelle installation. Si les pièces de votre modèle ne sont plus livrables, réparer ne fait généralement que reporter l\'échéance. Lors du diagnostic, nous indiquons honnêtement quand une réparation reste le meilleur choix.'],
        ],
        'en' => [
            ['question' => 'How often does a boiler need servicing?', 'answer' => 'In Flanders, periodic servicing is a legal requirement: every two years for gas appliances and annually for oil-fired ones. Beyond the obligation, servicing keeps efficiency up and catches developing faults before they turn into a breakdown.'],
            ['question' => 'I have heating but no hot water — what causes that?', 'answer' => 'On a combi boiler this usually points at the hot water function itself: a fouled or scaled heat exchanger, a failed three-way valve, or a sensor no longer passing on the hot water demand. Because heating still works, the burner is rarely the cause. Include the brand, model and any error code with your request so we can bring the right part.'],
            ['question' => 'When is replacing cheaper than repairing?', 'answer' => 'That depends on the age of the appliance, the availability of parts and the repair cost relative to a new installation. If parts for your model are no longer supplied, repairing usually just postpones the problem. At diagnosis we say plainly when a repair is still the better call.'],
        ],
    ],

    'airco' => [
        'nl' => [
            ['question' => 'Wat is het verschil tussen een split-unit en een multi-split?', 'answer' => 'Een split-unit koppelt één binnenunit aan één buitenunit en is de logische keuze voor één ruimte. Een multi-split laat meerdere binnenunits op dezelfde buitenunit werken, wat plaats en gevelruimte spaart wanneer u meerdere kamers wil koelen. De keuze hangt af van het aantal ruimtes, de gewenste onafhankelijke regeling per kamer en de plaats die er buiten beschikbaar is.'],
            ['question' => 'Heb ik toestemming nodig om een airco te plaatsen?', 'answer' => 'Dat hangt af van uw gebouw en gemeente. Bij een appartement geldt doorgaans het reglement van mede-eigendom voor alles wat aan de gevel of door een gemeenschappelijk deel gaat. Bij beschermd erfgoed of specifieke gemeentelijke voorschriften kunnen er bijkomende regels zijn. Wij bezorgen u de technische gegevens — plaats, afmetingen, geluidsniveau en condensafvoer — zodat u dit vooraf kunt laten nakijken.'],
            ['question' => 'Waarom moet een airco onderhouden worden?', 'answer' => 'Vervuilde filters en een vervuilde verdamper verlagen het rendement en verslechteren de luchtkwaliteit; staand condenswater is een bron van geurhinder. Daarnaast vraagt een installatie met koelmiddel een periodieke controle op lekken, uitgevoerd door een erkend F-gas technicus. Een toestel dat minder goed koelt dan vroeger heeft vaak gewoon onderhoud nodig, geen herstelling.'],
        ],
        'fr' => [
            ['question' => 'Quelle différence entre un split et un multi-split ?', 'answer' => 'Un split relie une unité intérieure à une unité extérieure : c\'est le choix logique pour une seule pièce. Un multi-split fait fonctionner plusieurs unités intérieures sur la même unité extérieure, ce qui économise de la place et de la surface de façade lorsque vous souhaitez refroidir plusieurs pièces. Le choix dépend du nombre de pièces, du besoin de régulation indépendante et de la place disponible à l\'extérieur.'],
            ['question' => 'Ai-je besoin d\'une autorisation pour installer une climatisation ?', 'answer' => 'Cela dépend de votre bâtiment et de votre commune. En appartement, le règlement de copropriété s\'applique généralement à tout ce qui touche la façade ou une partie commune. En cas de patrimoine protégé ou de prescriptions communales spécifiques, des règles supplémentaires peuvent s\'appliquer. Nous vous fournissons les données techniques — emplacement, dimensions, niveau sonore et évacuation des condensats — pour que vous puissiez le faire vérifier au préalable.'],
            ['question' => 'Pourquoi entretenir une climatisation ?', 'answer' => 'Des filtres et un évaporateur encrassés réduisent le rendement et dégradent la qualité de l\'air ; l\'eau de condensation stagnante est une source d\'odeurs. Par ailleurs, une installation contenant du fluide frigorigène demande un contrôle périodique d\'étanchéité réalisé par un technicien F-gaz agréé. Un appareil qui refroidit moins bien qu\'avant a souvent simplement besoin d\'un entretien, pas d\'une réparation.'],
        ],
        'en' => [
            ['question' => 'What is the difference between a split unit and a multi-split?', 'answer' => 'A split unit pairs one indoor unit with one outdoor unit and is the logical choice for a single room. A multi-split runs several indoor units off the same outdoor unit, saving space and façade area when you want to cool multiple rooms. The choice depends on the number of rooms, whether you need independent control per room, and the space available outside.'],
            ['question' => 'Do I need permission to install air conditioning?', 'answer' => 'That depends on your building and municipality. In an apartment, the co-ownership rules normally cover anything on the façade or passing through a common part. Protected heritage status or specific municipal rules can add further requirements. We supply the technical details — position, dimensions, sound level and condensate drainage — so you can have this checked beforehand.'],
            ['question' => 'Why does air conditioning need servicing?', 'answer' => 'Dirty filters and a fouled evaporator lower efficiency and worsen air quality; standing condensate is a source of odour. On top of that, an installation containing refrigerant needs periodic leak checking by a certified F-gas technician. A unit that cools less well than it used to often just needs servicing rather than repair.'],
        ],
    ],

    'plumbing' => [
        'nl' => [
            ['question' => 'Wat doe ik bij een waterlek terwijl ik op de technieker wacht?', 'answer' => 'Sluit eerst de hoofdkraan van de waterleiding en schakel de elektriciteit uit in de zone waar het water zit. Vang lekkend water op en verplaats wat beschadigd kan raken. Maak daarna foto\'s van de plaats van het lek: die helpen ons om het juiste materiaal mee te nemen in plaats van eerst te moeten terugrijden.'],
            ['question' => 'Kunnen jullie een volledige badkamer uitvoeren?', 'answer' => 'Ja. Wij begeleiden badkamerprojecten van ontwerp en afbraak tot de plaatsing van het nieuwe sanitair, inclusief de aansluitingen voor water en afvoer. Omdat verwarming en ventilatie in een badkamer meespelen, wordt dat in hetzelfde traject bekeken in plaats van achteraf.'],
            ['question' => 'Kunnen jullie snel komen bij een dringend lek?', 'answer' => 'Dringende waterlekken krijgen voorrang op geplande interventies. Een exacte tijd beloven wij niet vooraf: dat hangt af van de lopende planning en van uw locatie binnen het werkgebied. Wat wel helpt, is meteen doorgeven waar het lek zit en of het water afgesloten kan worden — daarmee schatten wij correct in hoe dringend het is.'],
        ],
        'fr' => [
            ['question' => 'Que faire en cas de fuite d\'eau en attendant le technicien ?', 'answer' => 'Fermez d\'abord le robinet principal d\'arrivée d\'eau et coupez l\'électricité dans la zone concernée. Récupérez l\'eau qui fuit et déplacez ce qui pourrait être endommagé. Prenez ensuite des photos de l\'endroit de la fuite : elles nous aident à emporter le bon matériel plutôt que de devoir repasser.'],
            ['question' => 'Réalisez-vous des salles de bain complètes ?', 'answer' => 'Oui. Nous accompagnons les projets de salle de bain de la conception et de la démolition jusqu\'à la pose du nouveau sanitaire, raccordements eau et évacuation compris. Comme le chauffage et la ventilation interviennent dans une salle de bain, ces aspects sont examinés dans le même parcours plutôt qu\'après coup.'],
            ['question' => 'Pouvez-vous intervenir rapidement en cas de fuite urgente ?', 'answer' => 'Les fuites d\'eau urgentes passent avant les interventions planifiées. Nous ne promettons pas d\'heure exacte à l\'avance : cela dépend du planning en cours et de votre localisation dans la zone d\'intervention. Ce qui aide : indiquer immédiatement où se situe la fuite et si l\'eau peut être coupée, afin que nous évaluions correctement l\'urgence.'],
        ],
        'en' => [
            ['question' => 'What should I do about a water leak while waiting for the technician?', 'answer' => 'First close the main water stopcock and switch off the electricity in the affected area. Catch the leaking water and move anything that could be damaged. Then photograph the location of the leak: that helps us bring the right materials rather than having to make a second trip.'],
            ['question' => 'Can you carry out a complete bathroom?', 'answer' => 'Yes. We handle bathroom projects from design and strip-out through to installing the new fixtures, including water supply and drainage connections. Because heating and ventilation both play a part in a bathroom, those are considered in the same process rather than afterwards.'],
            ['question' => 'Can you come quickly for an urgent leak?', 'answer' => 'Urgent water leaks take priority over scheduled work. We do not promise an exact time upfront: that depends on the current schedule and where you are within the service area. What does help is telling us straight away where the leak is and whether the water can be shut off, so we can judge the urgency correctly.'],
        ],
    ],

    'ventilation' => [
        'nl' => [
            ['question' => 'Wat is het verschil tussen ventilatie type C en type D?', 'answer' => 'Bij type C wordt de lucht mechanisch afgezogen en komt verse lucht via roosters natuurlijk binnen. Bij type D gebeuren zowel de aanvoer als de afvoer mechanisch, meestal met warmteterugwinning zodat de warmte van de afgevoerde lucht grotendeels behouden blijft. Type D levert meer comfort en minder warmteverlies, maar vraagt kanalen doorheen de woning en een consequenter onderhoud.'],
            ['question' => 'Hoe vaak moeten de filters vervangen worden?', 'answer' => 'Filters vragen meerdere keren per jaar aandacht, maar de juiste frequentie hangt af van uw omgeving en gebruik: een woning aan een drukke weg of met huisdieren vervuilt sneller dan een rustig gelegen woning. Een goede vuistregel is de filters te controleren bij elke seizoenwissel en te vervangen zodra ze zichtbaar verkleurd zijn.'],
            ['question' => 'Helpt ventilatie tegen schimmel in de badkamer?', 'answer' => 'Meestal wel, want schimmel ontstaat waar vocht blijft hangen op een koud oppervlak. Als de afzuiging in de badkamer te weinig debiet haalt — door een vuile filter, een dichtgeplakt rooster of een ontregelde installatie — droogt de ruimte niet meer op na een douche. Wij meten daarom eerst het werkelijke debiet voor er over een oplossing gesproken wordt.'],
        ],
        'fr' => [
            ['question' => 'Quelle différence entre la ventilation de type C et de type D ?', 'answer' => 'En type C, l\'air est extrait mécaniquement et l\'air neuf entre naturellement par des grilles. En type D, l\'amenée et l\'extraction sont toutes deux mécaniques, généralement avec récupération de chaleur : la chaleur de l\'air extrait est en grande partie conservée. Le type D offre plus de confort et moins de pertes, mais exige des gaines dans l\'habitation et un entretien plus rigoureux.'],
            ['question' => 'À quelle fréquence remplacer les filtres ?', 'answer' => 'Les filtres demandent une attention plusieurs fois par an, mais la bonne fréquence dépend de votre environnement et de votre usage : une habitation le long d\'une route fréquentée ou avec des animaux s\'encrasse plus vite qu\'une maison au calme. Une bonne règle : contrôler les filtres à chaque changement de saison et les remplacer dès qu\'ils sont visiblement décolorés.'],
            ['question' => 'La ventilation aide-t-elle contre les moisissures dans la salle de bain ?', 'answer' => 'Généralement oui, car les moisissures apparaissent là où l\'humidité stagne sur une surface froide. Si l\'extraction de la salle de bain n\'atteint plus un débit suffisant — filtre encrassé, grille obturée ou installation déréglée — la pièce ne sèche plus après une douche. Nous mesurons donc d\'abord le débit réel avant de parler de solution.'],
        ],
        'en' => [
            ['question' => 'What is the difference between type C and type D ventilation?', 'answer' => 'With type C, air is extracted mechanically while fresh air enters naturally through vents. With type D, both supply and extraction are mechanical, usually with heat recovery so most of the heat in the extracted air is retained. Type D delivers more comfort and less heat loss, but requires ducting through the home and more consistent maintenance.'],
            ['question' => 'How often do the filters need replacing?', 'answer' => 'Filters need attention several times a year, but the right interval depends on your surroundings and use: a home on a busy road or with pets fouls faster than one in a quiet spot. A sound rule of thumb is to check the filters at every change of season and replace them as soon as they are visibly discoloured.'],
            ['question' => 'Does ventilation help against mould in the bathroom?', 'answer' => 'Usually yes, because mould forms where moisture lingers on a cold surface. If bathroom extraction no longer reaches sufficient airflow — a dirty filter, a blocked vent or a system that has drifted out of adjustment — the room stops drying out after a shower. So we measure the actual airflow first, before discussing any solution.'],
        ],
    ],

    'water-softeners' => [
        'nl' => [
            ['question' => 'Is het leidingwater in de Druivenstreek hard?', 'answer' => 'In het grootste deel van Vlaams-Brabant, inclusief Tervuren, Overijse, Hoeilaart en Huldenberg, is het leidingwater hard. Dat merkt u aan kalkaanslag op kranen en douchewanden, witte vlekken op glaswerk en een boiler of warmtewisselaar die sneller verkalkt. De exacte hardheid verschilt per waterwingebied; uw waterleverancier publiceert de waarde voor uw adres.'],
            ['question' => 'Moet een waterverzachter zelf onderhouden worden?', 'answer' => 'Ja. Naast het bijvullen van zout heeft een toestel periodiek een reiniging en een controle van de regeneratiecyclus nodig. Een toestel dat te vaak of te weinig regenereert verbruikt onnodig zout en water, of laat kalk alsnog door. Bij een onderhoud controleren wij de instelling tegenover uw werkelijke waterverbruik en de gemeten hardheid.'],
            ['question' => 'Beschermt een waterverzachter mijn verwarmingsinstallatie?', 'answer' => 'Indirect wel. Verzacht water zet minder kalk af op warmtewisselaars en verwarmingselementen, wat het rendement op peil houdt en de levensduur van een boiler of combiketel ten goede komt. Het is echter geen vervanging voor het periodiek onderhoud van de ketel zelf.'],
        ],
        'fr' => [
            ['question' => 'L\'eau de distribution est-elle dure dans le Druivenstreek ?', 'answer' => 'Dans la majeure partie du Brabant flamand, y compris Tervuren, Overijse, Hoeilaart et Huldenberg, l\'eau de distribution est dure. Cela se remarque au calcaire sur les robinets et parois de douche, aux traces blanches sur la verrerie et à un boiler ou un échangeur qui s\'entartre plus vite. La dureté exacte varie selon la zone de captage ; votre distributeur publie la valeur correspondant à votre adresse.'],
            ['question' => 'Un adoucisseur doit-il lui-même être entretenu ?', 'answer' => 'Oui. Outre le rechargement en sel, l\'appareil nécessite périodiquement un nettoyage et un contrôle du cycle de régénération. Un appareil qui régénère trop souvent ou trop peu consomme inutilement du sel et de l\'eau, ou laisse malgré tout passer le calcaire. Lors d\'un entretien, nous vérifions le réglage par rapport à votre consommation réelle et à la dureté mesurée.'],
            ['question' => 'Un adoucisseur protège-t-il mon installation de chauffage ?', 'answer' => 'Indirectement oui. Une eau adoucie dépose moins de calcaire sur les échangeurs et les résistances, ce qui maintient le rendement et prolonge la durée de vie d\'un boiler ou d\'une chaudière combinée. Cela ne remplace toutefois pas l\'entretien périodique de la chaudière elle-même.'],
        ],
        'en' => [
            ['question' => 'Is the tap water hard in the Druivenstreek?', 'answer' => 'Across most of Flemish Brabant, including Tervuren, Overijse, Hoeilaart and Huldenberg, the tap water is hard. You notice it as limescale on taps and shower screens, white marks on glassware, and a water heater or heat exchanger that scales up faster. The exact hardness varies by supply area; your water company publishes the figure for your address.'],
            ['question' => 'Does a water softener itself need servicing?', 'answer' => 'Yes. Besides topping up salt, the unit periodically needs cleaning and a check of its regeneration cycle. A unit that regenerates too often or too rarely wastes salt and water, or lets limescale through anyway. During a service we check the settings against your actual water consumption and the measured hardness.'],
            ['question' => 'Does a water softener protect my heating system?', 'answer' => 'Indirectly, yes. Softened water deposits less limescale on heat exchangers and heating elements, which keeps efficiency up and extends the life of a water heater or combi boiler. It is not, however, a substitute for periodic servicing of the boiler itself.'],
        ],
    ],

    'cold-rooms' => [
        'nl' => [
            ['question' => 'De temperatuur in mijn koelcel loopt op — wat controleer ik eerst?', 'answer' => 'Kijk eerst of de deur correct sluit en of de dichting nog intact is, of de verdamper niet volledig is dichtgevroren, en of de condensor buiten niet verstopt zit met stof of bladeren. Die drie oorzaken verklaren een groot deel van de temperatuurproblemen. Blijft de temperatuur oplopen, verplaats dan de meest bederfbare goederen en meld het als dringend bij uw aanvraag.'],
            ['question' => 'Hoe vaak moet een koelinstallatie op lekken gecontroleerd worden?', 'answer' => 'De verplichte frequentie hangt af van de hoeveelheid koelmiddel in de installatie, uitgedrukt in CO2-equivalent, en van de aanwezigheid van een lekdetectiesysteem. De controle moet uitgevoerd worden door een erkend F-gas technicus en wordt in het installatiedossier bijgehouden. Wij bepalen bij de eerste interventie in welke categorie uw installatie valt.'],
            ['question' => 'Werken jullie ook voor horeca en voedingsbedrijven?', 'answer' => 'Ja. Van een kleine koelcel in een restaurantkeuken tot grotere koelruimtes bij voedings- en handelsbedrijven. Voor professionele klanten waar stilstand direct verlies betekent, wordt onderhoud bij voorkeur periodiek ingepland in plaats van pas na een defect.'],
        ],
        'fr' => [
            ['question' => 'La température de ma chambre froide monte — que vérifier d\'abord ?', 'answer' => 'Vérifiez d\'abord si la porte ferme correctement et si le joint est encore intact, si l\'évaporateur n\'est pas entièrement givré, et si le condenseur extérieur n\'est pas obstrué par la poussière ou les feuilles. Ces trois causes expliquent une grande partie des problèmes de température. Si la température continue de monter, déplacez les denrées les plus périssables et signalez-le comme urgent dans votre demande.'],
            ['question' => 'À quelle fréquence contrôler l\'étanchéité d\'une installation frigorifique ?', 'answer' => 'La fréquence obligatoire dépend de la quantité de fluide frigorigène de l\'installation, exprimée en équivalent CO2, et de la présence d\'un système de détection de fuite. Le contrôle doit être réalisé par un technicien F-gaz agréé et consigné dans le dossier de l\'installation. Nous déterminons lors de la première intervention dans quelle catégorie se situe la vôtre.'],
            ['question' => 'Travaillez-vous aussi pour l\'horeca et le secteur alimentaire ?', 'answer' => 'Oui. De la petite chambre froide dans une cuisine de restaurant aux espaces frigorifiques plus vastes des entreprises alimentaires et commerciales. Pour les clients professionnels où un arrêt signifie une perte immédiate, l\'entretien est de préférence planifié périodiquement plutôt qu\'après une panne.'],
        ],
        'en' => [
            ['question' => 'The temperature in my cold room is rising — what do I check first?', 'answer' => 'First check whether the door closes properly and the seal is still intact, whether the evaporator has not iced over completely, and whether the outdoor condenser is not clogged with dust or leaves. Those three causes account for a large share of temperature problems. If the temperature keeps climbing, move the most perishable goods and flag it as urgent in your request.'],
            ['question' => 'How often must a refrigeration system be leak-checked?', 'answer' => 'The mandatory interval depends on the refrigerant charge of the installation, expressed in CO2 equivalent, and on whether a leak detection system is fitted. The check has to be carried out by a certified F-gas technician and recorded in the installation logbook. We establish which category your installation falls into at the first visit.'],
            ['question' => 'Do you also work for catering and food businesses?', 'answer' => 'Yes. From a small cold room in a restaurant kitchen to larger cold storage at food and retail businesses. For commercial clients where downtime means immediate loss, maintenance is best scheduled periodically rather than only after a failure.'],
        ],
    ],
];
